//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.07 at 11:08:27 PM MSK 
//


package by.epam.training.entity;

public class Ingredients {

    private double water;
    private double sugar;
    private double vanillin;
    private String chocolateType;  //FIXME DO something

    public Ingredients(double water, double sugar, double vanillin, String chocolateType) {
        this.water = water;
        this.sugar = sugar;
        this.vanillin = vanillin;
        this.chocolateType = chocolateType;
    }

    public Ingredients() {
    }

    public double getWater() {
        return water;
    }

    public void setWater(double value) {
        this.water = value;
    }

    public double getSugar() {
        return sugar;
    }

    public void setSugar(double value) {
        this.sugar = value;
    }

    public double getVanillin() {
        return vanillin;
    }

    public void setVanillin(double value) {
        this.vanillin = value;
    }

    public String getChocolateType() {
        return chocolateType;
    }

    public void setChocolateType(String value) {
        this.chocolateType = value;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Ingredients{");
        sb.append("water=").append(water);
        sb.append(", sugar=").append(sugar);
        sb.append(", vanillin=").append(vanillin);
        sb.append(", chocolateType='").append(chocolateType).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
