//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.07 at 11:08:27 PM MSK 
//


package by.epam.training.entity;


import java.text.SimpleDateFormat;
import java.util.Calendar;

public class Production {

    private String manufactor;
    private String country;
    private Calendar foundingDate;

    public Production(String manufactor, String country, Calendar foundingDate) {
        this.manufactor = manufactor;
        this.country = country;
        this.foundingDate = foundingDate;
    }

    public Production() {
    }

    public String getManufactor() {
        return manufactor;
    }

    public void setManufactor(String value) {
        this.manufactor = value;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String value) {
        this.country = value;
    }

    public Calendar getFoundingDate() {
        return foundingDate;
    }

    public void setFoundingDate(Calendar value) {
        this.foundingDate = value;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Production{");
        sb.append("manufactor='").append(manufactor).append('\'');
        sb.append(", country='").append(country).append('\'');
        sb.append(", foundingDate=").append(new SimpleDateFormat("dd-MMM-yyyy").format(foundingDate.getTime()));
        sb.append('}');
        return sb.toString();
    }
}
