//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.07 at 11:08:27 PM MSK 
//


package by.train.candies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for energyValue complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="energyValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "energyValue", propOrder = {
    "proteins",
    "fats",
    "carbohydrates"
})
public class EnergyValue {

    protected double proteins;
    protected double fats;
    protected double carbohydrates;

    /**
     * Gets the value of the proteins property.
     * 
     */
    public double getProteins() {
        return proteins;
    }

    /**
     * Sets the value of the proteins property.
     * 
     */
    public void setProteins(double value) {
        this.proteins = value;
    }

    /**
     * Gets the value of the fats property.
     * 
     */
    public double getFats() {
        return fats;
    }

    /**
     * Sets the value of the fats property.
     * 
     */
    public void setFats(double value) {
        this.fats = value;
    }

    /**
     * Gets the value of the carbohydrates property.
     * 
     */
    public double getCarbohydrates() {
        return carbohydrates;
    }

    /**
     * Sets the value of the carbohydrates property.
     * 
     */
    public void setCarbohydrates(double value) {
        this.carbohydrates = value;
    }

}
