//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.07 at 11:08:27 PM MSK 
//


package by.train.candies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredients complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredients"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="chocolate-type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="milk"/&gt;
 *             &lt;enumeration value="dark"/&gt;
 *             &lt;enumeration value="white"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredients", propOrder = {
    "water",
    "sugar",
    "vanillin"
})
public class Ingredients {

    protected double water;
    protected double sugar;
    protected double vanillin;
    @XmlAttribute(name = "chocolate-type")
    protected String chocolateType;

    /**
     * Gets the value of the water property.
     * 
     */
    public double getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     */
    public void setWater(double value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     */
    public double getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     */
    public void setSugar(double value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the vanillin property.
     * 
     */
    public double getVanillin() {
        return vanillin;
    }

    /**
     * Sets the value of the vanillin property.
     * 
     */
    public void setVanillin(double value) {
        this.vanillin = value;
    }

    /**
     * Gets the value of the chocolateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChocolateType() {
        return chocolateType;
    }

    /**
     * Sets the value of the chocolateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChocolateType(String value) {
        this.chocolateType = value;
    }

}
