//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.05 at 04:16:33 PM MSK 
//


package by.training.candies;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.training.candies package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.training.candies
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SweetStuff }
     * 
     */
    public SweetStuff createSweetStuff() {
        return new SweetStuff();
    }

    /**
     * Create an instance of {@link SweetStuff.Candy }
     * 
     */
    public SweetStuff.Candy createSweetStuffCandy() {
        return new SweetStuff.Candy();
    }

    /**
     * Create an instance of {@link SweetStuff.Candy.Ingredients }
     * 
     */
    public SweetStuff.Candy.Ingredients createSweetStuffCandyIngredients() {
        return new SweetStuff.Candy.Ingredients();
    }

    /**
     * Create an instance of {@link SweetStuff.Candy.EnergyValue }
     * 
     */
    public SweetStuff.Candy.EnergyValue createSweetStuffCandyEnergyValue() {
        return new SweetStuff.Candy.EnergyValue();
    }

    /**
     * Create an instance of {@link SweetStuff.Candy.Production }
     * 
     */
    public SweetStuff.Candy.Production createSweetStuffCandyProduction() {
        return new SweetStuff.Candy.Production();
    }

}
