//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.05 at 04:16:33 PM MSK 
//


package by.training.candies;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="candy" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="ingredients"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="energyValue"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="production"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="manufactor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="stuffed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candy"
})
@XmlRootElement(name = "sweet-stuff")
public class SweetStuff {

    @XmlElement(required = true)
    protected List<SweetStuff.Candy> candy;

    /**
     * Gets the value of the candy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SweetStuff.Candy }
     * 
     * 
     */
    public List<SweetStuff.Candy> getCandy() {
        if (candy == null) {
            candy = new ArrayList<SweetStuff.Candy>();
        }
        return this.candy;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="ingredients"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="energyValue"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="production"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="manufactor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="stuffed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "energy",
        "ingredients",
        "energyValue",
        "production"
    })
    public static class Candy {

        @XmlElement(required = true)
        protected String name;
        protected int energy;
        @XmlElement(required = true)
        protected SweetStuff.Candy.Ingredients ingredients;
        @XmlElement(required = true)
        protected SweetStuff.Candy.EnergyValue energyValue;
        @XmlElement(required = true)
        protected SweetStuff.Candy.Production production;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "stuffed")
        protected String stuffed;
        @XmlAttribute(name = "id")
        protected Integer id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the energy property.
         * 
         */
        public int getEnergy() {
            return energy;
        }

        /**
         * Sets the value of the energy property.
         * 
         */
        public void setEnergy(int value) {
            this.energy = value;
        }

        /**
         * Gets the value of the ingredients property.
         * 
         * @return
         *     possible object is
         *     {@link SweetStuff.Candy.Ingredients }
         *     
         */
        public SweetStuff.Candy.Ingredients getIngredients() {
            return ingredients;
        }

        /**
         * Sets the value of the ingredients property.
         * 
         * @param value
         *     allowed object is
         *     {@link SweetStuff.Candy.Ingredients }
         *     
         */
        public void setIngredients(SweetStuff.Candy.Ingredients value) {
            this.ingredients = value;
        }

        /**
         * Gets the value of the energyValue property.
         * 
         * @return
         *     possible object is
         *     {@link SweetStuff.Candy.EnergyValue }
         *     
         */
        public SweetStuff.Candy.EnergyValue getEnergyValue() {
            return energyValue;
        }

        /**
         * Sets the value of the energyValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link SweetStuff.Candy.EnergyValue }
         *     
         */
        public void setEnergyValue(SweetStuff.Candy.EnergyValue value) {
            this.energyValue = value;
        }

        /**
         * Gets the value of the production property.
         * 
         * @return
         *     possible object is
         *     {@link SweetStuff.Candy.Production }
         *     
         */
        public SweetStuff.Candy.Production getProduction() {
            return production;
        }

        /**
         * Sets the value of the production property.
         * 
         * @param value
         *     allowed object is
         *     {@link SweetStuff.Candy.Production }
         *     
         */
        public void setProduction(SweetStuff.Candy.Production value) {
            this.production = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the stuffed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStuffed() {
            return stuffed;
        }

        /**
         * Sets the value of the stuffed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStuffed(String value) {
            this.stuffed = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="proteins" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="fats" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "proteins",
            "fats",
            "carbohydrates"
        })
        public static class EnergyValue {

            protected double proteins;
            protected int fats;
            protected int carbohydrates;

            /**
             * Gets the value of the proteins property.
             * 
             */
            public double getProteins() {
                return proteins;
            }

            /**
             * Sets the value of the proteins property.
             * 
             */
            public void setProteins(double value) {
                this.proteins = value;
            }

            /**
             * Gets the value of the fats property.
             * 
             */
            public int getFats() {
                return fats;
            }

            /**
             * Sets the value of the fats property.
             * 
             */
            public void setFats(int value) {
                this.fats = value;
            }

            /**
             * Gets the value of the carbohydrates property.
             * 
             */
            public int getCarbohydrates() {
                return carbohydrates;
            }

            /**
             * Sets the value of the carbohydrates property.
             * 
             */
            public void setCarbohydrates(int value) {
                this.carbohydrates = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="sugar" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="vanillin" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="chocolateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "water",
            "sugar",
            "vanillin"
        })
        public static class Ingredients {

            protected int water;
            protected int sugar;
            protected double vanillin;
            @XmlAttribute(name = "chocolateType")
            protected String chocolateType;

            /**
             * Gets the value of the water property.
             * 
             */
            public int getWater() {
                return water;
            }

            /**
             * Sets the value of the water property.
             * 
             */
            public void setWater(int value) {
                this.water = value;
            }

            /**
             * Gets the value of the sugar property.
             * 
             */
            public int getSugar() {
                return sugar;
            }

            /**
             * Sets the value of the sugar property.
             * 
             */
            public void setSugar(int value) {
                this.sugar = value;
            }

            /**
             * Gets the value of the vanillin property.
             * 
             */
            public double getVanillin() {
                return vanillin;
            }

            /**
             * Sets the value of the vanillin property.
             * 
             */
            public void setVanillin(double value) {
                this.vanillin = value;
            }

            /**
             * Gets the value of the chocolateType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChocolateType() {
                return chocolateType;
            }

            /**
             * Sets the value of the chocolateType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChocolateType(String value) {
                this.chocolateType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="manufactor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "manufactor",
            "country"
        })
        public static class Production {

            @XmlElement(required = true)
            protected String manufactor;
            @XmlElement(required = true)
            protected String country;

            /**
             * Gets the value of the manufactor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getManufactor() {
                return manufactor;
            }

            /**
             * Sets the value of the manufactor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setManufactor(String value) {
                this.manufactor = value;
            }

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

        }

    }

}
